### ISSUE TITLE
[Paper to Add] GraphIE (NAACL long paper)

### ISSUE THREAD

**Issue by zhijing-jin** [pfliu-nlp/Named-Entity-Recognition-NER-Papers#11]
Hi, 

First of all, thank you for creating this handy list!

Can you add this NER paper?
- GraphIE: A Graph-Based Framework for Information Extraction
- Concept: GCN, coreference consistency
- link: https://arxiv.org/abs/1810.13083

Again, thank you for maintaining such an awesome repo!

Best,
Zhijing

**Comment by pfliu-nlp** [comment]
thanks, and done~

**Comment by zhijing-jin** [comment]
Thank you! Btw, I am a current student collaborator with Prof Xipeng Qiu this year XD. I've heard labmates speaking very high of you. I enjoy reading your work :)!

Good luck at CMU!

**Comment by pfliu-nlp** [comment]
Thanks for your nice words. Prof. Qiu is an excellent advisor.
Looking forward to your work.

Best,
Pengfei

**Comment by zhijing-jin** [comment]
:)
