### ISSUE TITLE
More info on ReCoNLL and PLONER

### ISSUE THREAD

**Issue by mayhewsw** [pfliu-nlp/Named-Entity-Recognition-NER-Papers#6]
The link for ReCoNLL appears to be broken. 

Can you say where PLONER came from? Both datasets look interesting.

**Comment by mayhewsw** [comment]
I see that these came from: http://pfliu.com/InterpretNER/rethink-ner.pdf

**Comment by pfliu-nlp** [comment]
Cool! That's it.
